### ISSUE TITLE
Cannot load portapps.json

### ISSUE THREAD

**Issue by jhon65496** [portapps/smartgit-portable#43]
Downloaded from the link `https://github.com/portapps/smartgit-portable/releases `
File - **smartgit-portable-win64.exe ** | 4.31 MB | Dec 24, 2023

I get an error:
![image](https://github.com/portapps/smartgit-portable/assets/128128859/96655d9c-fe74-4d6b-bea0-cd8257fbd56b)

Error message:
```
Cannot load portapps.json: 
open d:\Soft\Smartgit\Smartgit_23.1.1-36\fl\fmportapp.json: 
The system cannot find the file specified.
```

**Use**
Win 10x64

**Comment by crazy-max** [comment]
You need to download the bundle, not just the wrapper, see download links on the website: https://portapps.io/app/smartgit-portable/#download
